[package]
name = "tippster"
version = "2.0.2"
description = "Tippster - 10-Finger spielerisch lernen"
authors = ["Tippster"]
license = "GPL-3.0"
edition = "2024"
rust-version = "1.90"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "tippster_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[build-dependencies]
tauri-build = { version = "2.7.0", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.12.0", features = [] }
tauri-plugin-log = "2"
tauri-plugin-updater = "2"
